services:
  mirage-ai:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "8005:8005"
    volumes:
      - .:/app
      - mirage-data:/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    env_file:
      - .env

volumes:
  mirage-data:
